CREATE TABLE IF NOT EXISTS contract_recycle (
    id UInt64,
    indebted_name Nullable(String),
    indebted_id Nullable(String),
    creditor_name Nullable(String),
    creditor_id Nullable(String),
    description Nullable(String),
    status Nullable(Int32),
    start_date Nullable(DateTime),
    end_date Nullable(DateTime),
    return_type Nullable(String),
    reason_type Nullable(String),
    detail_reason Nullable(String),
    salary Nullable(Int64),
    tariff Nullable(Int64),
    file Nullable(String),
    interest Nullable(Float64),
    refund Nullable(Float64),
    dept_id Nullable(Int64),
    create_time Nullable(DateTime),
    update_time Nullable(DateTime),
    creator Nullable(String),
    updater Nullable(String),
    deleted Nullable(UInt8),
    archive_time DateTime
) ENGINE = ReplacingMergeTree(archive_time)
ORDER BY id;
